/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface BrandLogoProps {
  src: string;
  alt: string;
}

const BrandLogo: React.FC<BrandLogoProps> = ({ src, alt }) => {
  return (
    <img
      loading="lazy"
      src={src}
      alt={alt}
      className="object-contain shrink-0 self-stretch my-auto aspect-[4.24] w-[157px]"
    />
  );
};

export default BrandLogo;
