/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ImageGallery: React.FC = () => {
  return (
    <div className="flex flex-wrap gap-4 mt-12 w-full min-h-[619px] max-md:mt-10 max-md:max-w-full">
      <div className="flex overflow-hidden flex-1 shrink justify-center h-full basis-0 min-w-[240px] max-md:max-w-full">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/d19dae65fbad6c8374b2ae19b3bd50290fd2b9613b9d7a76591d7100121e533f?placeholderIfAbsent=true&apiKey=93385a543be74ee9937d50a97d245785"
          alt="Gallery image 1"
          className="object-contain flex-1 shrink w-full aspect-[0.97] basis-0 min-w-[240px] max-md:max-w-full"
        />
      </div>
      <div className="flex flex-col flex-1 shrink justify-center basis-0 min-w-[240px] max-md:max-w-full">
        <div className="flex overflow-hidden flex-1 gap-2.5 justify-center items-start size-full max-md:max-w-full">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/140316b45ff327db655a948c304a87072a14368a166a5e4850c832f2f491f7f3?placeholderIfAbsent=true&apiKey=93385a543be74ee9937d50a97d245785"
            alt="Gallery image 2"
            className="object-contain flex-1 shrink w-full aspect-[1.99] basis-0 min-w-[240px] max-md:max-w-full"
          />
        </div>
        <div className="flex overflow-hidden flex-1 justify-center items-start mt-4 size-full max-md:max-w-full">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/b049763d173b87a9267014426bf803aa4e1b4d4e35bd4ed7cd6d93e8a76e78c5?placeholderIfAbsent=true&apiKey=93385a543be74ee9937d50a97d245785"
            alt="Gallery image 3"
            className="object-contain flex-1 shrink w-full aspect-[1.99] basis-0 min-w-[240px] max-md:max-w-full"
          />
        </div>
      </div>
    </div>
  );
};

export default ImageGallery;
