/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface StatisticItemProps {
  value: string;
  label: string;
}

const StatisticItem: React.FC<StatisticItemProps> = ({ value, label }) => (
  <div className="flex flex-col justify-center self-stretch my-auto">
    <h2 className="text-5xl font-bold leading-none max-md:text-4xl">
      {value}
      <span className="text-cyan-500">+</span>
    </h2>
    <p className="mt-2 text-xl leading-tight">{label}</p>
  </div>
);

export default StatisticItem;
