/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface ButtonProps {
  children: React.ReactNode;
}

const Button: React.FC<ButtonProps> = ({ children }) => {
  return (
    <button className="gap-2.5 self-stretch px-5 py-2.5 bg-cyan-500 rounded-[1000px] text-base font-bold text-white">
      {children}
    </button>
  );
};

export default Button;
