/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface TestimonialCardProps {
  avatarSrc: string;
  logoSrc: string;
  name: string;
  company: string;
  review: string;
}

const TestimonialCard: React.FC<TestimonialCardProps> = ({
  avatarSrc,
  logoSrc,
  name,
  company,
  review,
}) => {
  return (
    <article className="flex flex-1 shrink gap-6 justify-center items-start self-stretch p-6 my-auto basis-0 bg-stone-50 min-w-[240px] max-md:px-5">
      <div className="flex flex-col flex-1 shrink justify-center w-full basis-0 min-w-[240px]">
        <div className="flex gap-4 justify-center items-center self-start">
          <img
            loading="lazy"
            src={avatarSrc}
            alt={`${name}'s avatar`}
            className="object-contain shrink-0 self-stretch my-auto w-12 aspect-square rounded-[100px]"
          />
          <img
            loading="lazy"
            src={logoSrc}
            alt={`${company} logo`}
            className="object-contain shrink-0 self-stretch my-auto w-44 aspect-[5.18]"
          />
        </div>
        <div className="flex flex-col justify-center mt-3 w-full text-base text-black">
          <p className="font-semibold">
            {name} <span className="text-neutral-500">reviewed</span> {company}
          </p>
          <p className="mt-1 leading-6">{review}</p>
        </div>
      </div>
    </article>
  );
};

export default TestimonialCard;
